### ISSUE TITLE
Does not work in iOS13.4 simulator

### ISSUE THREAD

**Issue by sam-w** [auth0/SimpleKeychain#90] opened 2020-03-25 07:36 UTC
### Description
When using the iOS13.4 simulator, `SimpleKeychain` reports that it saved successfully. When I try to retrieve the saved object, I get empty data.

### Reproduction

- Add this to a fresh Xcode project , e.g. in the AppDelegate.

```swift
let keychain = A0SimpleKeychain()
keychain.setString("foo", forKey: "f")
let string = keychain.string(forKey: "f")!
assert(string == "foo")
```

- Run on iOS 12.4 sim, no assert.
- Run on iOS 13.4 sim, assertion failed.

### Environment

- **Version of this library used:** 0.11.0
- **Version of the platform or framework used, if applicable:** iOS 13.4 simulator

**Comment by mikchmie** [comment] 2020-03-25 09:31
On iOS 13.3 simulator it works as well. So just the newest iOS simulator seems to be affected.

**Comment by sam-w** [comment] 2020-03-25 09:36
Possibly related to https://stackoverflow.com/questions/56700680/keychain-query-always-returns-errsecitemnotfound-after-upgrading-to-ios-13

**Comment by sam-w** [comment] 2020-03-25 09:37
https://github.com/evgenyneu/keychain-swift _does_ work on iOS 13.4 simulator, so might provide a point of comparison.

**Comment by cocojoe** [comment] 2020-03-25 10:19
Thanks for reporting @sam-w , does it work on 13.4 device?

**Comment by mikchmie** [comment] 2020-03-25 10:24
@cocojoe Yes, it works on a physical device with 13.4.

**Comment by BaranEm** [comment] 2020-03-25 10:29
Having the same issue here on iOS 13.4 simulator.

**Comment by cocojoe** [comment] 2020-03-25 11:55
Updated my device to 13.4, test suite results:

13.4 Device - All Passing
13.4 Simulator - Failing

Odd situation, working on device implies that code is fine. However, it should work on the simulator of course. So possibly simulator bug or a configuration issue of some kind? Since it was mentioned keychain-swift is okay (I've not checked)

**Comment by cocojoe** [comment] 2020-03-25 12:28
Did a little exploring and going through previous commits, if you comment this line out then all tests pass in Simulator.

https://github.com/auth0/SimpleKeychain/blob/master/SimpleKeychain/A0SimpleKeychain.m#L305

**Comment by cocojoe** [comment] 2020-03-25 13:51
> https://github.com/evgenyneu/keychain-swift _does_ work on iOS 13.4 simulator, so might provide a point of comparison.

Had a look, as suspected it doesn't make any use of ```LAContext``` that I can see.

**Comment by Widcket** [comment] 2020-03-25 20:21
This seems to be a bug in the iOS 13.4 simulator, as it's reproducible just with the Keychain API:
```swift
let laContext = LAContext()
let key = "foo"

let query = [
    kSecClass as String: kSecClassGenericPassword,
    kSecAttrService as String: key,
    kSecValueData as String: "bar".data(using: .utf8)!,
    // kSecUseAuthenticationContext as String: laContext
] as [String : Any]

SecItemAdd(query as CFDictionary, nil)

let loadQuery = [
    kSecClass as String: kSecClassGenericPassword,
    kSecAttrService as String: key,
    kSecReturnData as String: kCFBooleanTrue!,
    // kSecUseAuthenticationContext as String: laContext
] as [String : Any]

var dataTypeRef: CFTypeRef?
SecItemCopyMatching(loadQuery as CFDictionary, &dataTypeRef)

print(String(data: (dataTypeRef as? Data) ?? "nope!".data(using: .utf8)!, encoding: .utf8)!)
```
Uncomment the lines and it will print `nope!` instead of `bar`.

**Comment by Widcket** [comment] 2020-03-25 20:45
@sam-w and all, one possible workaround is to disable `kSecUseAuthenticationContext` for simulator targets. I've set up a [branch](https://github.com/auth0/SimpleKeychain/tree/fix/simulator-workaround) with the changes, can you give it a try?

**Comment by sam-w** [comment] 2020-03-26 00:46
@Widcket still fails for me on 13.4 with your branch.

**Comment by dionc** [comment] 2020-03-26 07:54
Probably related to this issue, in the 13.4 simulator `hasValueForKey` returns `true` for any key:

```
(lldb) po self
<A0SimpleKeychain: 0x7fd916471b80>

(lldb) po hasValue(forKey: UUID().uuidString)
true
```

**Comment by cocojoe** [comment] 2020-03-26 09:21
@sam-w can you comment out linehttps://github.com/auth0/SimpleKeychain/blob/master/SimpleKeychain/A0SimpleKeychain.m#L305 
please and feedback.

@Widcket I don't think the branch you provided has the changes committed.

**Comment by Widcket** [comment] 2020-03-26 10:06
@cocojoe you're right, my bad. I've just pushed the commit.

**Comment by Widcket** [comment] 2020-03-26 10:43
@dionc that method uses `SecItemCopyMatching` under the hood. It seems to return a successful status whenever a `kSecUseAuthenticationContext` is included:

```swift
let laContext = LAContext()

let loadQuery = [
  kSecClass as String: kSecClassGenericPassword,
  kSecAttrService as String: UUID().uuidString,
  kSecUseAuthenticationContext as String: laContext
] as [String : Any]

let result = SecItemCopyMatching(loadQuery as CFDictionary, nil)
print("Result: \(result == errSecSuccess)") // Result: true
```

**Closed** 2020-03-26 20:21 UTC
Labels: needs investigation

**Comment by Widcket** [comment] 2020-03-26 21:41
@sam-w and all, the workaround is out in the https://github.com/auth0/SimpleKeychain/releases/tag/0.11.1. Thanks for the report and the input.

**Comment by sam-w** [comment] 2020-03-27 01:12
Thanks @Widcket. Given that keychain access has proved to be an issue as iOS continues to develop, I'd like to have the option of using an alternative to SimpleKeychain in the future. Please consider reopening https://github.com/auth0/Auth0.swift/pull/367 so we can achieve that.

**Comment by ezzz** [comment] 2020-03-27 18:26
Thanks for the correction!
